name: CI

on: [push]

jobs:
  build:
    container:
      image: anatol1988/elm:0.19.1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build js from elm sources
      run: |
        .github/optimize.sh src/Main.elm;
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: build
